import { createPlaywrightTestSuite } from '../helpers/PlaywrightTestFramework'

const { test, describe, expect } = createPlaywrightTestSuite()

describe('AppSidebarBase mockup', () => {
  test('renders status sections and keeps sandbox interactions local', async ({ testSetup }) => {
    const { mainWindow } = await testSetup.setupAndStart({ workspace: { scenario: 'minimal' } })
    await mainWindow.getByTestId('nav-button-mockups').click()
    await mainWindow.getByTestId('mockup-tab-appsidebarbase').click()
    const mockup = mainWindow.getByTestId('app-sidebar-base-mockup')
    const active = mockup.getByTestId('mock-status-section-active')
    const liveSidebarText = await mainWindow.getByTestId('app-sidebar').textContent()
    await expect(mockup.locator('.status-header')).toHaveText(['ACTIVE 20', 'BACKLOG 2'])
    await mockup.getByRole('button', { name: 'Show Completed Prompts', exact: true }).click()
    await mockup.getByRole('button', { name: 'Show Archived Prompts', exact: true }).click()
    await expect(mockup.locator('.status-header')).toHaveText(['COMPLETED 1', 'ARCHIVED 1', 'ACTIVE 20', 'BACKLOG 2'])
    await mockup.getByRole('button', { name: 'Show Completed Prompts', exact: true }).click()
    await mockup.getByRole('button', { name: 'Show Archived Prompts', exact: true }).click()
    const initialHeight = (await active.boundingBox())!.height
    const sash = (await mockup.getByRole('button', { name: 'Resize Backlog section' }).boundingBox())!
    await mainWindow.mouse.move(sash.x + sash.width / 2, sash.y + 2)
    await mainWindow.mouse.down()
    await mainWindow.mouse.move(sash.x + sash.width / 2, sash.y + 32)
    await mainWindow.mouse.up()
    await expect.poll(async () => Math.abs((await active.boundingBox())!.height - initialHeight - 30)).toBeLessThanOrEqual(2)
    await mockup.getByRole('button', { name: 'Collapse All Categories', exact: true }).click()
    await expect(mockup.getByRole('button', { name: 'Expand category Research' })).toBeVisible()
    await mockup.getByRole('button', { name: 'Expand All Categories', exact: true }).click()
    await mockup.getByRole('button', { name: 'Add Category', exact: true }).click()
    await mockup.getByLabel('Category name').fill('Sandbox category')
    await mockup.getByRole('button', { name: 'Create Category', exact: true }).click()
    await expect(mockup.getByRole('button', { name: 'Collapse category Sandbox category' })).toHaveCount(1)
    await mockup.locator('.tree-category-content').filter({ hasText: 'Research' }).hover()
    await mockup.getByRole('button', { name: 'Add Prompt to top of category Research', exact: true }).click()
    await expect(mockup.locator('.status-header')).toHaveText(['ACTIVE 21', 'BACKLOG 2'])
    await expect(mockup.getByRole('button', { name: 'New Prompt', exact: true })).toHaveAttribute('aria-current', 'true')
    await expect(mainWindow.getByTestId('app-sidebar')).toHaveText(liveSidebarText!)
    await mainWindow.screenshot({ path: 'temp/app-sidebar-base-mockup.png' })
  })
})
