import { createPlaywrightTestSuite } from '../helpers/PlaywrightTestFramework'
import { readTextFile } from '../helpers/PromptPersistenceTestHelpers'
import { join } from 'node:path'

/** Playwright primitives configured for the Electron integration environment. */
const { test, describe, expect } = createPlaywrightTestSuite()

/** Finds the one persistent log entry containing a unique test marker. */
const getMarkedLogEntry = (logContents: string, marker: string): string =>
  logContents.split('\n\n').find((entry) => entry.includes(marker)) ?? ''

describe('Persistent renderer logging', () => {
  test('writes complete stacks for handled and unhandled renderer errors', async ({
    testSetup,
    electronApp
  }) => {
    /** Running renderer whose error is forwarded through preload to the main process. */
    const { mainWindow } = await testSetup.setupAndStart()
    /** Unique text that identifies the errors generated by this test. */
    const errorMarker = `renderer-stack-${Date.now().toString(36)}`

    await electronApp.evaluate(async ({ app }) => {
      app.emit('test-initialize-persistent-logging')
    })

    await mainWindow.evaluate((marker) => {
      /** Leaf frame that constructs the handled renderer Error captured by console.error. */
      function handledRendererStackLeaf(): void {
        console.error(new Error(`${marker}-handled`))
      }

      /** Parent frame used to prove handled logging retains more than the first location. */
      function handledRendererStackRoot(): void {
        handledRendererStackLeaf()
      }

      /** Frame that proves string-only console errors receive a captured call-site stack. */
      function stringRendererStack(): void {
        console.error(`${marker}-string`)
      }

      /** Schedules a named throwing frame that reaches the global error event. */
      function uncaughtRendererStack(): void {
        setTimeout(function throwUncaughtRendererError() {
          throw new Error(`${marker}-uncaught`)
        })
      }

      /** Frame retained when a rejected promise reaches the global rejection event. */
      function rejectedRendererStack(): void {
        void Promise.reject(new Error(`${marker}-rejected`))
      }

      handledRendererStackRoot()
      stringRendererStack()
      uncaughtRendererStack()
      rejectedRendererStack()
    }, errorMarker)

    /** Application log lives in the same in-memory filesystem as settings and prompts. */
    const logPath = join(await electronApp.evaluate(({ app }) => app.getPath('logs')), 'cthulhu-prompt.log')
    /** Reads the production logger's output through the application's filesystem provider. */
    const readPersistentLog = async (): Promise<string> =>
      await readTextFile(electronApp, logPath)

    await expect
      .poll(async () => {
        /** Latest log contents used to wait for every asynchronous error report. */
        const logContents = await readPersistentLog()
        return (
          getMarkedLogEntry(logContents, `${errorMarker}-handled`).includes(
            'at handledRendererStackLeaf'
          ) &&
          getMarkedLogEntry(logContents, `${errorMarker}-handled`).includes(
            'at handledRendererStackRoot'
          ) &&
          getMarkedLogEntry(logContents, `${errorMarker}-string`).includes(
            'at stringRendererStack'
          ) &&
          getMarkedLogEntry(logContents, `${errorMarker}-uncaught`).includes(
            'at throwUncaughtRendererError'
          ) &&
          getMarkedLogEntry(logContents, `${errorMarker}-rejected`).includes(
            'at rejectedRendererStack'
          )
        )
      })
      .toBe(true)

    /** Log contents inspected after the asynchronous renderer IPC has arrived. */
    const logContents = await readPersistentLog()
    expect(getMarkedLogEntry(logContents, `${errorMarker}-handled`)).toContain(
      'at handledRendererStackLeaf'
    )
    expect(getMarkedLogEntry(logContents, `${errorMarker}-handled`)).toContain(
      'at handledRendererStackRoot'
    )
    expect(getMarkedLogEntry(logContents, `${errorMarker}-string`)).toContain(
      'at stringRendererStack'
    )
    expect(getMarkedLogEntry(logContents, `${errorMarker}-uncaught`)).toContain(
      'at throwUncaughtRendererError'
    )
    expect(getMarkedLogEntry(logContents, `${errorMarker}-rejected`)).toContain(
      'at rejectedRendererStack'
    )

    testSetup.removeRendererErrorsContaining(errorMarker)
  })
})
