import { createPlaywrightTestSuite } from '../helpers/PlaywrightTestFramework'

const { test, describe, expect } = createPlaywrightTestSuite()

describe('PromptFolderScreenBase mockup', () => {
  test('keeps status workflows and category changes inside the sandbox', async ({ testSetup }) => {
    const { mainWindow } = await testSetup.setupAndStart({ workspace: { scenario: 'minimal' } })
    await mainWindow.getByTestId('nav-button-mockups').click()
    await mainWindow.getByTestId('mockup-tab-promptfolderscreenbase').click()
    const mockup = mainWindow.getByTestId('base-prompt-folder-mockup')
    const liveSidebarText = await mainWindow.getByTestId('app-sidebar').textContent()
    const filters = mockup.getByRole('group', { name: 'Filter prompts' })
    await expect(filters.getByRole('button')).toHaveText(['Active 8', 'Backlog 0', 'Completed 0', 'Archived 0'])
    const prompt = mockup.getByTestId('base-mockup-prompt-editor-base-requirements')
    await prompt.getByRole('button', { name: 'Move prompt to Backlog', exact: true }).click()
    await filters.getByRole('button', { name: 'Backlog 1', exact: true }).click()
    await expect(prompt).toBeVisible()
    await expect(prompt.getByRole('button', { name: 'Copy prompt', exact: true })).toHaveCount(0)
    await prompt.getByRole('button', { name: /^Change status:/ }).click()
    await mainWindow.getByRole('menuitem', { name: 'Complete Move this prompt to completed', exact: true }).click()
    await filters.getByRole('button', { name: 'Completed 1', exact: true }).click()
    await prompt.getByRole('button', { name: 'Archive prompt', exact: true }).click()
    await filters.getByRole('button', { name: 'Archived 1', exact: true }).click()
    await expect(prompt).toBeVisible()
    await filters.getByRole('button', { name: 'Active 7', exact: true }).click()
    await mockup.getByRole('button', { name: 'Add category', exact: true }).click()
    const dialog = mainWindow.getByRole('dialog', { name: 'Create Category', exact: true })
    const name = dialog.getByRole('textbox', { name: 'Category Name', exact: true })
    await expect(name).toBeFocused()
    await expect(dialog).toContainText('Add a category to this root folder.')
    await expect(dialog.getByRole('button', { name: 'Create Category', exact: true })).toBeDisabled()
    await expect.poll(async () => Math.abs((await dialog.boundingBox())!.width - 540)).toBeLessThanOrEqual(1)
    await expect.poll(async () => Math.abs((await name.boundingBox())!.width - 220)).toBeLessThanOrEqual(1)
    const existingName = await mockup.locator('.base-folder-title').first().innerText()
    await name.fill(` ${existingName.toUpperCase()} `)
    await expect(dialog).toContainText('A category with this name already exists')
    await expect(name).toHaveAttribute('aria-invalid', 'true')
    await name.fill('Sandbox category')
    await mainWindow.screenshot({ path: 'temp/mockup-create-category-dialog.png' })
    await mainWindow.getByRole('button', { name: 'Create Category', exact: true }).click()
    const category = mockup.locator('.base-folder-section').filter({ hasText: 'Sandbox category' })
    await expect(category).toBeVisible()
    await category.getByRole('button', { name: 'Hide category settings', exact: true }).click()
    await expect(category.locator('.base-folder-settings')).toHaveCount(0)
    await category.getByRole('button', { name: 'Collapse category prompts', exact: true }).click()
    await expect(category.locator('.base-folder-children')).toHaveCount(0)
    await category.getByRole('button', { name: 'Rename category', exact: true }).click()
    const rename = mainWindow.getByRole('dialog', { name: 'Rename Category', exact: true })
    await expect(rename.getByRole('textbox')).toHaveValue('Sandbox category')
    await rename.getByRole('textbox').fill('Renamed category')
    await rename.getByRole('button', { name: 'Rename Category', exact: true }).click()
    const renamed = mockup.locator('.base-folder-section').filter({ hasText: 'Renamed category' })
    await renamed.getByRole('button', { name: 'Delete category', exact: true }).click()
    const deletion = mainWindow.getByRole('dialog', { name: 'Delete Category', exact: true })
    await expect(deletion).toContainText('Its contents will move to Uncategorized.')
    await mainWindow.keyboard.press('Escape')
    await expect(deletion).toHaveCount(0)
    await expect(renamed).toBeVisible()
    await renamed.getByRole('button', { name: 'Delete category', exact: true }).click()
    await deletion.getByRole('button', { name: 'Delete Category', exact: true }).click()
    await expect(renamed).toHaveCount(0)
    await expect(mainWindow.getByTestId('app-sidebar')).toHaveText(liveSidebarText!)
    await mockup.getByRole('button', { name: 'Find in Folder (Control + F)', exact: true }).click()
    await mockup.getByRole('textbox', { name: 'Find', exact: true }).fill('Map the current implementation')
    await expect(mockup.getByRole('search')).toContainText('1 of 1')
    await mockup.getByRole('button', { name: 'Next match', exact: true }).click()
    const firstPrompt = mockup.getByTestId('base-mockup-prompt-editor-base-discovery')
    await expect(firstPrompt).toBeInViewport()
    await mockup.getByRole('button', { name: 'Close find', exact: true }).click()
    await mockup.evaluate((element) => { element.style.width = '680px' })
    await expect.poll(async () => Math.abs((await firstPrompt.locator('.base-prompt-title-area').boundingBox())!.height - 109)).toBeLessThanOrEqual(1)
    await firstPrompt.getByRole('button', { name: /^Change status:/ }).click()
    await expect(mainWindow.getByRole('menuitem', { name: 'Todo Move back to active todo status', exact: true })).toBeVisible()
    const statusMenu = mainWindow.getByRole('menu', { name: 'Change status More Options', exact: true })
    await expect(statusMenu.locator('.base-status-menu-subtitle')).toHaveText([
      'Move back to active todo status', 'Save this prompt for future work', 'Move this prompt to completed'
    ])
    await expect.poll(async () => Math.abs((await statusMenu.boundingBox())!.width - 260)).toBeLessThanOrEqual(1)
    await expect.poll(async () => Math.abs((await statusMenu.getByRole('menuitem').first().boundingBox())!.height - 50)).toBeLessThanOrEqual(1)
    await mainWindow.screenshot({ path: 'temp/mockup-status-menu.png' })
    await mainWindow.keyboard.press('Escape')
    await firstPrompt.getByRole('button', { name: 'Archive prompt More Options', exact: true }).click()
    const deleteMenu = mainWindow.getByRole('menu', { name: 'Prompt actions', exact: true })
    await expect(deleteMenu.getByRole('menuitem')).toHaveText(/Delete Prompt\s*Permanently delete this prompt/)
    await expect.poll(async () => Math.abs((await deleteMenu.boundingBox())!.width - 240)).toBeLessThanOrEqual(1)
    await expect(deleteMenu.locator('svg')).toHaveCount(1)
    await mainWindow.screenshot({ path: 'temp/mockup-delete-menu.png' })
    await mainWindow.keyboard.press('Escape')
    await mockup.evaluate((element) => {
      element.style.width = ''
      element.querySelector('.base-content-viewport')!.scrollTop = 0
    })
    await mainWindow.screenshot({ path: 'temp/prompt-folder-screen-base-mockup.png' })
  })
})
