export const PROMPT_FOLDER_FIND_TITLE_SECTION_KEY = 'title'
export const PROMPT_FOLDER_FIND_BODY_SECTION_KEY = 'body'
export const PROMPT_FOLDER_FIND_FOLDER_DESCRIPTION_SECTION_KEY = 'folder-description'
